spring:
  profiles:
    active: mysql
#  batch:
#    job:
#      enabled: false
#      names: myJobs

jasypt:
  encryptor:
    bean: OnyouBatchEncryptor

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
      url: jdbc:mysql://onyou.ccnmi4nbea4z.ap-northeast-2.rds.amazonaws.com:3306/onyou-dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username: onyou
      password: ENC(uFp/gDGtH3l24RVEeK2/bTTzJ5k+hBvK)
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

