name: Onyou_batch_CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
     -
        name: Checkout
        uses: actions/checkout@v2
     -
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
     -   
        name: Grant execution permission for mvnw
        run: chmod +x mvnw
     -
        name: Build with Maven
        run: ./mvnw package -DskipTests=true
     -   
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_JJUNYONG_ONYOU }}
     -
        name: Docker Build and push
        run: |
          docker build -t onyou-batch .
          docker tag onyou-batch ${{ secrets.DOCKER_USERNAME }}/onyou-batch:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/onyou-batch:${GITHUB_SHA::7}
